project:
  type: website
  output-dir: docs

website:
  title: "Talks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [Default, Styles/website_styles.scss]
    mainfont: Quicksand
    toc: true
    page-layout: full
    
editor: visual

